stages:
  prepare:
    params:
      split: 0.20
      seed: 20170428

  featurize:
    params:
      max_features: 3000
      ngrams: 2

  train:
    params:
      seed: 20170428
      n_est: 100
      min_split: 64
      a: 1
      a1: 1
      a2: 1
